# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: drupal-docker:latest

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

# Select what we should cache between builds
cache:
  paths:
  - vendor/

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
  - mariadb

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mariadb/)
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_DATABASE: "docker"
  MYSQL_USER: "docker"
  MYSQL_PASSWORD: "docker"
  # Drupal settings
  SIMPLETEST_DB: "mysql://docker:docker@mariadb/docker"
  SIMPLETEST_BASE_URL: "http://localhost"
  BROWSERTEST_OUTPUT_DIRECTORY: "/tmp/tests"
  SYMFONY_DEPRECATIONS_HELPER: "weak"
  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome",{"chrome":{"switches":["disable-gpu","window-size=1280,1024"]}},"http://selenium:4444/wd/hub"]'

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  script:
  - vendor/bin/phpunit --coverage-text --colors=never

test_core:
  script:
  - /etc/init.d/apache2 start
  - vendor/bin/phpunit --colors=never --exclude-group ignore -c web/core --group breadcrumb web/core
